// app/api/profile/route.ts
// Profil business (business_profiles) — lecture + update depuis /settings
// ✅ Cohérent avec le code existant : colonnes snake_case (cf. app/api/onboarding/answers/route.ts)
// - GET: retourne le profil (ou null)
// - PATCH: met à jour un sous-ensemble de champs safe (sans casser l'onboarding)
// ✅ MULTI-PROJETS : scoped au projet actif via cookie


import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { getSupabaseServerClient } from "@/lib/supabaseServer";
import { supabaseAdmin } from "@/lib/supabaseAdmin";
import { getActiveProjectId } from "@/lib/projects/activeProject";
import { upsertByProject } from "@/lib/projects/upsertByProject";
import { QUIZ_GRADIENTS } from "@/lib/quizBranding";

export const dynamic = "force-dynamic";

type AnyRecord = Record<string, any>;

// Pre-distilled selling points generated by /api/offers/sales-arguments.
// Persisted alongside the offer so the editor and content prompts can
// read them in one DB hit. Schema kept loose because it's user-editable
// via a different endpoint — we just want to preserve it through the
// /api/profile save instead of stripping it.
const SalesArgumentBulletSchema = z
  .object({
    benefit: z.string().trim().max(500),
    consequence: z.string().trim().max(500),
    angle: z.string().trim().max(80).optional().default(""),
    hook_idea: z.string().trim().max(300).optional().default(""),
  })
  .passthrough();

const SalesArgumentsSchema = z
  .object({
    generated_at: z.string().optional(),
    persona_signature: z.string().optional(),
    offer_signature: z.string().optional(),
    model: z.string().optional(),
    bullets: z.array(SalesArgumentBulletSchema).max(20).optional().default([]),
  })
  .passthrough()
  .nullable()
  .optional();

const OfferItemSchema = z.object({
  name: z.string().trim().max(200).default(""),
  type: z.string().trim().max(80).optional().default(""),
  price: z.union([z.string().max(40), z.number()]).optional().default(""),
  salesCount: z.union([z.string().max(40), z.number()]).optional().default(""),
  link: z.string().trim().max(400).optional().default(""),
  promise: z.string().trim().max(500).optional().default(""),
  description: z.string().trim().max(2000).optional().default(""),
  target: z.string().trim().max(500).optional().default(""),
  format: z.string().trim().max(200).optional().default(""),
  // Optional binding for the Systeme.io sales sync. Stored alongside
  // the offer so the matcher in lib/sio/salesSync can attribute SIO
  // sales to the right offer with 100% confidence.
  sio_product_id: z.string().trim().max(80).nullable().optional(),
  sales_arguments: SalesArgumentsSchema,
});

const UpdateSchema = z.object({
  first_name: z.string().trim().max(120).optional(),
  country: z.string().trim().max(120).optional(),
  niche: z.string().trim().max(5000).optional(),
  mission: z.string().trim().max(10000).optional(),

  business_maturity: z.string().trim().max(120).optional(),
  offers_status: z.string().trim().max(120).optional(),

  main_goals: z.array(z.string().trim().max(200)).max(10).optional(),
  preferred_content_types: z.array(z.string().trim().max(120)).max(12).optional(),
  tone_preference: z.string().trim().max(120).optional(),

  offers: z.array(OfferItemSchema).max(50).optional(),

  privacy_url: z.string().trim().max(500).optional(),
  terms_url: z.string().trim().max(500).optional(),
  cgv_url: z.string().trim().max(500).optional(),

  sio_user_api_key: z.string().trim().max(200).optional(),
  sio_api_key_name: z.string().trim().max(100).optional(),
  // ID affilié Tipote — utilisé sur le footer du popquiz public
  // pour rediriger vers tipote.fr/part-tiquiz?sa=<id> et toucher
  // des commissions. Format SIO : "sa" + 32 hex.
  tipote_affiliate_id: z.string().trim().max(200).optional(),

  content_locale: z.string().trim().max(10).optional(),
  address_form: z.enum(["tu", "vous"]).optional(),
  // Notifications email a chaque nouvelle reponse (opt-out, par projet).
  // Cf. migration 20260718_business_profiles_notify_responses.sql.
  notify_responses: z.boolean().optional(),
  revenue_goal_monthly: z.string().trim().max(200).optional(),

  // Branding — nullable so a paid user can clear the value (e.g. remove
  // their custom logo and fall back to no logo). The UI sends null on
  // remove; without .nullable() Zod 400s and the save silently fails.
  brand_font: z.string().trim().max(100).nullable().optional(),
  brand_color_base: z.string().trim().max(30).nullable().optional(),
  brand_color_accent: z.string().trim().max(30).nullable().optional(),
  brand_logo_url: z.string().trim().max(1000).nullable().optional(),
  // Favicon custom (Gwenn, 23 mai 2026). Affiché dans l'onglet
  // navigateur UNIQUEMENT sur les pages publiques servies via un
  // custom domain vérifié de ce projet.
  brand_favicon_url: z.string().trim().max(1000).nullable().optional(),
  brand_author_photo_url: z.string().trim().max(1000).nullable().optional(),
  brand_tone_of_voice: z.string().trim().max(500).nullable().optional(),

  // Palettes de couleurs nommées de l'user (max 10 palettes × 5 couleurs).
  // Stockées en JSONB sur business_profiles, ré-utilisables sur tous
  // les éditeurs (quiz, survey, popquiz). Validation stricte du format
  // pour ne pas laisser passer de blob arbitraire.
  saved_palettes: z.array(z.object({
    id: z.string().min(1).max(80),
    name: z.string().trim().max(60).default(""),
    colors: z.array(z.string().regex(/^#[0-9a-fA-F]{6}$/)).max(5).default([]),
  })).max(10).optional(),

  linkedin_url: z.string().trim().max(500).optional(),
  instagram_url: z.string().trim().max(500).optional(),
  youtube_url: z.string().trim().max(500).optional(),
  website_url: z.string().trim().max(500).optional(),
  tiktok_url: z.string().trim().max(500).optional(),
  pinterest_url: z.string().trim().max(500).optional(),
  threads_url: z.string().trim().max(500).optional(),
  facebook_url: z.string().trim().max(500).optional(),

  // Phase B (Adeline, 19 mai 2026) : défauts pixels Meta + Google
  // pré-remplis sur les nouveaux quizzes du créateur. Nullable pour
  // que le user puisse effacer.
  default_meta_pixel_id: z.string().trim().max(200).nullable().optional(),
  default_ga4_measurement_id: z.string().trim().max(200).nullable().optional(),
  default_google_ads_conversion_id: z.string().trim().max(200).nullable().optional(),
  default_google_ads_conversion_label: z.string().trim().max(200).nullable().optional(),
  // Token Conversions API Meta (secret server-side) — apparié au pixel
  // par défaut pour l'envoi des Lead côté serveur (dédup avec le pixel).
  default_meta_capi_token: z.string().trim().max(500).nullable().optional(),

  // Nom de marque affiché à la place de "Tipote" dans og:site_name + le
  // <title> sur les routes publiques servies via un custom domain
  // (Adeline, 19 mai 2026). Cf. migration 20260519_business_profiles_share_site_name.
  share_site_name: z.string().trim().max(60).nullable().optional(),

  // Modele de design PAR PROJET (Brique 1) — estampille la mise en forme
  // preferee sur les nouveaux quiz/sondages. Sets fermes ; le degrade est
  // valide contre QUIZ_GRADIENTS (valeur inconnue -> null, jamais de 400).
  default_question_layout: z.enum(["centered", "left", "split"]).nullable().optional(),
  default_intro_layout: z.enum(["card", "cover"]).nullable().optional(),
  default_button_shape: z.enum(["pill", "rounded", "square"]).nullable().optional(),
  default_answer_layout: z.enum(["auto", "grid", "list"]).nullable().optional(),
  default_background_style: z.enum(["solid", "gradient"]).nullable().optional(),
  default_background_gradient: z
    .string()
    .trim()
    .max(30)
    .nullable()
    .optional()
    .transform((v) => (v == null ? v : v in QUIZ_GRADIENTS ? v : null)),

  custom_links: z.array(z.object({
    label: z.string().trim().max(100),
    url: z.string().trim().max(500),
  })).max(10).optional(),

  // Storytelling (6-step founder journey)
  storytelling: z
    .object({
      situation_initiale: z.string().trim().max(2000).optional().default(""),
      element_declencheur: z.string().trim().max(2000).optional().default(""),
      peripeties: z.string().trim().max(2000).optional().default(""),
      moment_critique: z.string().trim().max(2000).optional().default(""),
      resolution: z.string().trim().max(2000).optional().default(""),
      situation_finale: z.string().trim().max(2000).optional().default(""),
    })
    .optional(),

  // ─── Module Compta (étape 1b) ─────────────────────────────────
  // Statut principal — null efface la config, sinon une des 3 valeurs.
  accounting_status: z
    .enum([
      // FR
      "particulier",
      "auto_entrepreneur",
      "sasu",
      "sas",
      "sarl",
      "eurl",
      // CH
      "independant_ch",
      "sarl_ch",
      "sa_ch",
      // PT
      "trabalhador_independente_pt",
      "eni_pt",
      "lda_unipessoal_pt",
      "lda_pt",
      "sa_pt",
      // BE
      "independant_principal_be",
      "independant_complementaire_be",
      "srl_be",
      "sa_be",
      // ES
      "autonomo_es",
      "slu_es",
      "sl_es",
      "sa_es",
      // CA
      "travailleur_autonome_ca",
      "entreprise_individuelle_ca",
      "inc_provincial_ca",
      "inc_federal_ca",
      // US
      "sole_proprietorship_us",
      "single_member_llc_us",
      "multi_member_llc_us",
      "c_corp_us",
      "s_corp_us",
    ])
    .nullable()
    .optional(),

  // Particulier
  particulier_revenue_type: z.enum(["bnc_accessoire", "bic_accessoire", "autre"]).nullable().optional(),

  // Auto-entrepreneur
  ae_activity_type: z.enum(["vente", "services_bic", "services_bnc", "mixte"]).nullable().optional(),
  ae_started_at: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable().optional(),
  ae_acre: z.boolean().optional(),
  ae_versement_liberatoire: z.boolean().optional(),
  ae_vat_franchise: z.boolean().optional(),
  ae_urssaf_periodicity: z.enum(["mensuelle", "trimestrielle"]).nullable().optional(),
  ae_vat_regime: z.enum(["reel_mensuel", "reel_trimestriel", "simplifie"]).nullable().optional(),

  // SASU — SIREN strict 9 chiffres ; côté front on l'aide en bloquant
  // les caractères non numériques mais on revalide en zod côté serveur.
  sasu_siren: z.string().regex(/^\d{9}$/).nullable().optional(),
  sasu_fiscal_year_calendar: z.boolean().optional(),
  sasu_fiscal_year_start_month: z.number().int().min(1).max(12).nullable().optional(),
  sasu_vat_regime: z.enum(["reel_mensuel", "reel_trimestriel", "simplifie"]).nullable().optional(),
  sasu_vat_intra_enabled: z.boolean().optional(),
  sasu_dirigeant_remunere: z.boolean().optional(),

  // EURL / SARL — spécificités au-delà du tronc commun "société à l'IS"
  // qui réutilise les colonnes sasu_*.
  eurl_is_election: z.boolean().optional(),
  sarl_gerant_majoritaire: z.boolean().optional(),

  // Suisse — phase 1n
  ch_canton: z
    .enum([
      "AG", "AI", "AR", "BE", "BL", "BS", "FR", "GE", "GL", "GR", "JU", "LU",
      "NE", "NW", "OW", "SG", "SH", "SO", "SZ", "TG", "TI", "UR", "VD", "VS",
      "ZG", "ZH",
    ])
    .nullable()
    .optional(),
  ch_vat_assujetti: z.boolean().optional(),
  ch_vat_periodicity: z
    .enum(["mensuelle", "trimestrielle", "semestrielle", "annuelle"])
    .nullable()
    .optional(),
  ch_vat_method: z.enum(["effective", "tdfn"]).nullable().optional(),
  ch_started_at: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable().optional(),

  // Portugal — phase 1o
  pt_nif: z.string().regex(/^\d{9}$/).nullable().optional(),
  pt_region: z.enum(["continente", "madeira", "acores"]).nullable().optional(),
  pt_iva_isento: z.boolean().optional(),
  pt_iva_periodicity: z.enum(["mensal", "trimestral"]).nullable().optional(),
  pt_tax_regime: z.enum(["simplificado", "organizada"]).nullable().optional(),
  pt_started_at: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable().optional(),

  // Belgique — phase 1p
  be_region: z.enum(["wallonie", "flandre", "bruxelles"]).nullable().optional(),
  be_company_number: z.string().regex(/^\d{10}$/).nullable().optional(),
  be_vat_franchise: z.boolean().optional(),
  be_vat_periodicity: z.enum(["mensuelle", "trimestrielle"]).nullable().optional(),
  be_intra_eu_listing: z.boolean().optional(),
  be_started_at: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable().optional(),

  // Espagne — phase 1q
  es_community: z
    .enum([
      "AN", "AR", "AS", "IB", "CN", "CB", "CL", "CM", "CT", "VC",
      "EX", "GA", "MD", "MC", "NC", "PV", "RI", "CE", "ML",
    ])
    .nullable()
    .optional(),
  es_company_number: z.string().trim().max(20).nullable().optional(),
  es_iva_regime: z.enum(["general", "simplificado", "recargo_equivalencia", "exencion"]).nullable().optional(),
  es_iva_periodicity: z.enum(["mensual", "trimestral"]).nullable().optional(),
  es_redeme: z.boolean().optional(),
  es_irpf_method: z.enum(["directa", "objetiva"]).nullable().optional(),
  es_started_at: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable().optional(),

  // Canada — phase 1r
  ca_province: z
    .enum([
      "QC", "ON", "BC", "AB", "MB", "SK",
      "NS", "NB", "NL", "PE",
      "YT", "NT", "NU",
    ])
    .nullable()
    .optional(),
  ca_business_number: z.string().trim().max(30).nullable().optional(),
  ca_gst_registered: z.boolean().optional(),
  ca_gst_periodicity: z.enum(["mensuelle", "trimestrielle", "annuelle"]).nullable().optional(),
  ca_petit_fournisseur: z.boolean().optional(),
  ca_fiscal_year_calendar: z.boolean().optional(),
  ca_fiscal_year_start_month: z.number().int().min(1).max(12).nullable().optional(),
  ca_started_at: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable().optional(),

  // États-Unis — phase 1s
  us_state: z
    .enum([
      "AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA",
      "HI","ID","IL","IN","IA","KS","KY","LA","ME","MD",
      "MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ",
      "NM","NY","NC","ND","OH","OK","OR","PA","RI","SC",
      "SD","TN","TX","UT","VT","VA","WA","WV","WI","WY",
      "DC",
    ])
    .nullable()
    .optional(),
  us_ein: z.string().trim().max(20).nullable().optional(),
  us_llc_tax_classification: z
    .enum(["disregarded", "partnership", "s_corp", "c_corp"])
    .nullable()
    .optional(),
  us_sales_tax_states: z.array(z.string().regex(/^[A-Z]{2}$/)).max(51).optional(),
  us_fiscal_year_calendar: z.boolean().optional(),
  us_fiscal_year_start_month: z.number().int().min(1).max(12).nullable().optional(),
  us_started_at: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable().optional(),
  // accounting_status_configured_at est défini côté serveur dans le PATCH
  // ci-dessous, pas accepté en input.

  // Auto-comments automation
  auto_comment_style_ton: z.string().trim().max(40).optional(),
  auto_comment_langage: z
    .object({
      mots_cles: z.array(z.string().max(80)).max(20).optional(),
      emojis: z.array(z.string().max(10)).max(20).optional(),
      expressions: z.array(z.string().max(200)).max(20).optional(),
    })
    .optional(),
  auto_comment_objectifs: z.array(z.string().trim().max(80)).max(5).optional(),
});

export async function GET() {
  try {
    const supabase = await getSupabaseServerClient();
    const {
      data: { user },
      error: userError,
    } = await supabase.auth.getUser();

    if (userError || !user) {
      return NextResponse.json({ ok: false, error: "Unauthorized" }, { status: 401 });
    }

    const projectId = await getActiveProjectId(supabase, user.id);

    let query = supabase
      .from("business_profiles")
      .select("*")
      .eq("user_id", user.id);

    if (projectId) query = query.eq("project_id", projectId);

    const { data, error } = await query.maybeSingle();

    if (error) return NextResponse.json({ ok: false, error: error.message }, { status: 400 });

    // Enrichit avec profiles.plan (BUG Laurent 2 juin 2026 : depuis
    // l'introduction du multiprofils, /api/profile renvoie la row
    // business_profiles per-projet, qui n'a pas la colonne `plan`.
    // Conséquence : TOUS les composants qui lisaient profile.plan
    // (AutoCommentSettings, etc.) voyaient undefined → fallback "free"
    // → Elite bloqué dans Settings → Boost). Le plan vit sur la table
    // `profiles` (global par user, pas par projet — c'est de l'abonnement).
    let profileOut = data ?? null;
    try {
      const { data: planRow } = await supabaseAdmin
        .from("profiles")
        .select("plan")
        .eq("id", user.id)
        .maybeSingle();
      const plan = (planRow as { plan?: string | null } | null)?.plan ?? null;
      profileOut = { ...(profileOut ?? {}), plan };
    } catch (e) {
      console.error("[profile.GET] plan enrichment failed", e);
      // Fail-open : on renvoie ce qu'on a (sans plan) → AutoCommentSettings
      // affichera le gate Pro/Elite mais l'user peut quand même charger
      // ses autres réglages.
    }

    // Décrypte la clé SIO pour la renvoyer au front (l'éditeur en a
    // besoin pour pré-remplir le champ password-masqué). Le front
    // affiche la clé en type=password — l'utilisateur doit cliquer 👁
    // pour la lire en clair. Côté DB elle reste en ciphertext.
    if (profileOut) {
      const enc = (profileOut as { sio_user_api_key_enc?: string | null }).sio_user_api_key_enc;
      if (enc) {
        try {
          const { resolveSioApiKey } = await import("@/lib/sio/resolveApiKey");
          const plain = await resolveSioApiKey(supabase, user.id, projectId);
          profileOut = { ...profileOut, sio_user_api_key: plain ?? "" };
        } catch (e) {
          console.error("[profile.GET] SIO decrypt failed:", e);
          // Fail-safe : on retourne le profil sans la clé plutôt que
          // de bloquer le chargement complet du settings.
          profileOut = { ...profileOut, sio_user_api_key: "" };
        }
      }
    }

    return NextResponse.json({ ok: true, profile: profileOut }, { status: 200 });
  } catch (e) {
    return NextResponse.json(
      { ok: false, error: e instanceof Error ? e.message : "Unknown error" },
      { status: 500 },
    );
  }
}

export async function PATCH(req: NextRequest) {
  try {
    const supabase = await getSupabaseServerClient();
    const {
      data: { user },
      error: userError,
    } = await supabase.auth.getUser();

    if (userError || !user) {
      return NextResponse.json({ ok: false, error: "Unauthorized" }, { status: 401 });
    }

    let body: unknown;
    try {
      body = await req.json();
    } catch {
      return NextResponse.json({ ok: false, error: "Invalid JSON" }, { status: 400 });
    }

    const parsed = UpdateSchema.safeParse(body);
    if (!parsed.success) {
      const flat = parsed.error.flatten();
      const fieldErrors = flat.fieldErrors ?? {};
      const summary = Object.entries(fieldErrors)
        .map(([k, msgs]) => `${k}: ${(msgs as string[]).join(", ")}`)
        .join("; ");
      console.error("[PATCH /api/profile] Validation error:", JSON.stringify(flat));
      return NextResponse.json(
        { ok: false, error: summary || "Validation error", details: flat },
        { status: 400 },
      );
    }

    const patch = parsed.data;

    // Rien à updater
    if (Object.keys(patch).length === 0) {
      return NextResponse.json({ ok: true, profile: null }, { status: 200 });
    }

    const projectId = await getActiveProjectId(supabase, user.id);

    const row: Record<string, unknown> = {
      user_id: user.id,
      ...patch,
      updated_at: new Date().toISOString(),
    };
    if (projectId) row.project_id = projectId;

    // Si l'user (re)définit son accounting_status, on stamp la
    // date côté serveur — l'input client ne peut pas la spoofer.
    // Quand on bascule explicitement à null (effacer la config), on
    // remet aussi le timestamp à null pour rester cohérent.
    if (Object.prototype.hasOwnProperty.call(patch, "accounting_status")) {
      const next = (patch as { accounting_status?: unknown }).accounting_status;
      (patch as Record<string, unknown>).accounting_status_configured_at =
        next ? new Date().toISOString() : null;
    }

    // SIO API key encryption at rest. Béné 2026-05-04 : avant ce
    // commit la clé partait en clair dans la DB. On encrypte
    // (AES-256-GCM par-user-DEK, lib/piiCrypto) et on stocke dans
    // sio_user_api_key_enc. La colonne plaintext est nullée pour
    // que le ciphertext soit la seule représentation persistée.
    const writePatch: Record<string, unknown> = { ...patch };
    if (writePatch.sio_user_api_key !== undefined) {
      const raw = String(writePatch.sio_user_api_key ?? "").trim();
      if (raw) {
        try {
          const { encryptSioApiKey } = await import("@/lib/sio/resolveApiKey");
          writePatch.sio_user_api_key_enc = await encryptSioApiKey(
            supabase, user.id, raw,
          );
          writePatch.sio_user_api_key = null;
        } catch (e) {
          console.error("[profile] SIO encrypt failed (storing plaintext as fallback):", e);
          // Fail-safe : si l'encryption casse (env mal configuré, DEK
          // indisponible), on laisse le plaintext partir comme avant
          // pour ne pas bloquer l'utilisateur — la régression de sécu
          // est strictement bornée à ce cas dégradé.
        }
      } else {
        // L'utilisateur a vidé le champ → clear les DEUX colonnes.
        writePatch.sio_user_api_key = null;
        writePatch.sio_user_api_key_enc = null;
      }
    }

    // Update-then-insert scoped by user + project (safe for multi-project)
    const { data, error } = await upsertByProject({
      supabase,
      table: "business_profiles",
      userId: user.id,
      projectId,
      data: { ...writePatch, updated_at: new Date().toISOString() },
      select: "*",
    });

    if (error) {
      console.error("[PATCH /api/profile] DB error:", error.message, error.code);
      return NextResponse.json({ ok: false, error: error.message }, { status: 400 });
    }

    // Fan out legal URLs to all the user's hosted pages whenever
    // any of privacy_url / terms_url / cgv_url is in this patch.
    // Settings is the source of truth — pages mirror it (column +
    // content_data + html_snapshot rebuild) so the live footer
    // updates without the user having to open the page editor.
    // Non-blocking: the response returns immediately, the rebuild
    // chews through the user's pages in the background.
    const legalUrlTouched =
      "privacy_url" in patch || "terms_url" in patch || "cgv_url" in patch;
    if (legalUrlTouched) {
      (async () => {
        try {
          const { syncLegalUrlsToUserPages } = await import("@/lib/pages/syncLegalUrls");
          const result = await syncLegalUrlsToUserPages(user.id, {
            privacy_url: patch.privacy_url,
            terms_url: patch.terms_url,
            cgv_url: patch.cgv_url,
          });
          console.log("[profile] legal URL fan-out:", { userId: user.id, ...result });
        } catch (e) {
          console.error("[profile] legal URL fan-out failed:", e);
        }
      })();
    }

    // Auto-register SIO webhooks when API key is saved/changed (non-blocking)
    if (patch.sio_user_api_key !== undefined) {
      const apiKey = String(patch.sio_user_api_key ?? "").trim();
      (async () => {
        try {
          const { registerSioWebhooks, deregisterSioWebhooks } = await import("@/lib/sio/webhookRegistration");
          if (apiKey) {
            // Key saved or changed → register webhooks
            await deregisterSioWebhooks({ userId: user.id, projectId });
            const result = await registerSioWebhooks({ userId: user.id, projectId, apiKey });
            if (result.errors.length > 0) {
              console.warn("[profile] SIO webhook registration warnings:", result.errors);
            }
          } else {
            // Key cleared → deregister
            await deregisterSioWebhooks({ userId: user.id, projectId });
          }
        } catch (e) {
          console.error("[profile] SIO webhook auto-registration failed:", e);
        }
      })();
    }

    // Live strategy invalidation : si l'user touche un champ qui nourrit
    // le prompt stratégie, on marque le plan existant comme "stale" pour
    // que la page /strategy affiche un bandeau "Recalculer". On ne
    // déclenche PAS la regen ici (trop lourd, latence sur la PATCH).
    //
    // Béné feedback Monique 2026-05-04 : la stratégie ne se rafraîchissait
    // pas avec les nouvelles infos. Premier pas vers le pipeline live.
    const STRATEGY_AFFECTING_FIELDS = [
      "revenue_goal_monthly", "niche", "mission", "business_maturity",
      "offers", "has_offers", "main_goal", "main_goals", "biggest_blocker",
      "time_available", "business_model", "persona", "target_audience_short",
    ] as const;
    const strategyAffected = STRATEGY_AFFECTING_FIELDS.some((k) => k in patch);
    if (strategyAffected) {
      (async () => {
        try {
          const { data: existing } = await supabase
            .from("business_plan")
            .select("plan_json")
            .eq("user_id", user.id)
            .maybeSingle();
          const planJson = (existing as { plan_json?: Record<string, unknown> } | null)?.plan_json;
          if (planJson && typeof planJson === "object") {
            const next = { ...planJson, is_stale: true, stale_since: new Date().toISOString() };
            await upsertByProject({
              supabase,
              table: "business_plan",
              userId: user.id,
              projectId,
              data: { plan_json: next, updated_at: new Date().toISOString() },
            });
          }
        } catch (e) {
          console.warn("[profile] strategy stale-flag failed (non-blocking):", e);
        }
      })();
    }

    return NextResponse.json({ ok: true, profile: data ?? null }, { status: 200 });
  } catch (e) {
    console.error("[PATCH /api/profile] Unexpected error:", e);
    return NextResponse.json(
      { ok: false, error: e instanceof Error ? e.message : "Unknown error" },
      { status: 500 },
    );
  }
}
